# https://quarto.org/docs/books/book-output.html
project:
  type: book
  output-dir: docs

book: 
  title: "Foundations of Spatial Data Science"
  author: "Jon Reades"
  image: "img/casa_logo.jpg"
  date: "1/6/2022"
  repo-url: https://github.com/jreades/fsds/
  repo-actions: [edit]
  chapters:
    - index.qmd
    - format.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - week9.qmd
    - week10.qmd
    - week11.qmd
    - references.qmd
  appendices:
    - appendices/docker.qmd
    - appendices/conda.qmd
  number-depth: 3
  toc-depth: 2
  sidebar:
    title: "CASA0013"
    style: floating
    reader-mode: true
  navbar:
    logo: "img/casa_logo.jpg"
    collapse: true
    collapse-below: lg
    background: light
  favicon: "img/favicon.ico"	
  page-navigation: true
  page-footer: 
    left: "Copyright 2022, Jon Reades" 
    right: 
      - icon: github
        href: https://github.com/jreades/fsds
      - icon: twitter 
        href: https://twitter.com/jreades

bibliography: bib/Readings.bib
csl: bib/chicago-author-date.csl

highlight-style: pygments
format:
  html:
    theme: cosmo
    code-copy: true
    code-link: true
    #cover-image: cover.png
  pdf:
    #cover-image: cover-highres.png
    documentclass: scrbook
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
