# https://quarto.org/docs/books/book-output.html
project:
  type: website
  output-dir: docs
  preview:
    port: 4200
  render:
    - "!bib/"
    - "!lectures/*.md"
    - "*.qmd"
  resources:
    - "bib"
    - "img"
    - "practicals"

website:
  title: "Foundations of Spatial Data Science"
  author: "Jon Reades"
  image: "img/casa_logo.jpg"
  date: "6/1/2022"
  repo-url: https://github.com/jreades/fsds/
  repo-actions: [issue]
  number-depth: 3
  toc-depth: 3
  favicon: "img/favicon.ico"	
  page-navigation: true
  page-footer: 
    left: "Copyright 2022, Jon Reades" 
    right: 
      - icon: github
        href: https://github.com/jreades/fsds
      - icon: twitter 
        href: https://twitter.com/jreades
  navbar:
    logo: "img/casa_logo.jpg"
    collapse: true
    collapse-below: md
    background: light
    left:
      - text: "Welcome"
        href: index.qmd
      - text: "Getting Started"
        href: setup.qmd
      - text: "Week-by-Week"
        href: sessions.qmd
      - text: "Assessments"
        href: assessments.qmd

  sidebar:



    - id: setup
      collapse-level: 2
      tyle: "floating"
      contents:
        - text: "Getting Started"
          href: setup.qmd
        - text: "Health Check"
          href: setup/health.qmd
        - section: "Tools"
          contents:
          - setup/git.qmd
          - setup/markdown.qmd
          - setup/docker.qmd
          - setup/conda.qmd
        - text: "Code Camp"
          href: setup/code_camp.qmd

    - id: assessments
      collapse-level: 2
      tyle: "floating"
      contents:
        - text: "Assessments"
          href: assessments.qmd
        - section: "Elements"
          contents:
          - assessments/audit.qmd
          - section: "Data+Policy Briefing (50%)"
            href: assessments/group.qmd
            contents:
              - assessments/briefing.qmd
              - assessments/code.qmd
              - assessments/models.qmd
              - assessments/restrictions.qmd
              - assessments/marking.qmd
          - assessments/individual.qmd
      
    - id: schedule
      collapse-level: 2
      contents:
        - text: "Week-by-Week"
          href: sessions.qmd
        - section: "Schedule"
          contents:
            - text: "1. Setting Up"
              href: week1.qmd
            - text: "2. Foundations (Pt.1)"
              href: week2.qmd
            - text: "3. Foundations (Pt.2)"
              href: week3.qmd
            - text: "4. Objects"
              href: week4.qmd
            - text: "5. Numeric Data"
              href: week5.qmd
            - text: "Reading Week"
              href: week6.qmd
            - text: "6. Spatial Data"
              href: week7.qmd
            - text: "7. Textual Data"
              href: week8.qmd
            - text: "8. Dimensions in Data"
              href: week9.qmd
            - text: "9. Visualising Data"
              href: week10.qmd
            - text: "10. Grouping Data"
              href: week11.qmd
        - text: "References"
          href: references.qmd

book: 
  title: "Foundations of Spatial Data Science"
  author: "Jon Reades"
  image: "img/casa_logo.jpg"
  date: "6/1/2022"
  repo-url: https://github.com/jreades/fsds/
  repo-actions: [edit]
  chapters:
    - index.qmd
    - format.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - week9.qmd
    - week10.qmd
    - week11.qmd
    - assessments.qmd
    - references.qmd
  appendices:
    - appendices/docker.qmd
    - appendices/conda.qmd
  number-depth: 3
  toc-depth: 3
  sidebar:
    title: "CASA0013"
    style: floating
    reader-mode: true
  navbar:
    logo: "img/casa_logo.jpg"
    collapse: true
    collapse-below: lg
    background: light
  favicon: "img/favicon.ico"	
  page-navigation: true
  page-footer: 
    left: "Copyright 2022, Jon Reades" 
    right: 
      - icon: github
        href: https://github.com/jreades/fsds
      - icon: twitter 
        href: https://twitter.com/jreades

bibliography: bib/Readings.bib
csl: bib/chicago-author-date.csl

highlight-style: pygments
format:
  html:
    theme: cosmo
    code-copy: true
    code-link: true
    #cover-image: cover.png
  pdf:
    #cover-image: cover-highres.png
    documentclass: scrbook
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
