# https://quarto.org/docs/books/book-output.html
project:
  type: website
  output-dir: docs
  preview:
    port: 4200
  render:
    - "!bib/"
    - "!slideas/*"
    - "!lectures/*.md"
    - "*.qmd"
  resources:
    - "bib"
    - "img"
    - "practicals"

website:
  title: "Foundations of Spatial Data Science"
  author: "Jon Reades"
  image: "img/CASA_Logo_no_text.png"
  date: "6/1/2022"
  repo-url: https://github.com/jreades/fsds/
  repo-actions: [issue]
  number-depth: 2
  favicon: "/img/favicon.ico"
  page-navigation: true
  reader-mode: true
  page-footer: 
    left: "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 2022, Jon Reades"
    center: "![](/img/favicon-16x16.png){.height:10px} Foundations of Spatial Data Science"
    right: 
      - icon: github
        href: https://github.com/jreades/fsds
      - icon: twitter 
        href: https://twitter.com/jreades
  navbar:
    background: primary
    search: true
    logo: "/img/CASA_Logo_no_text.png"
    collapse: true
    collapse-below: md
    left:
      - text: "Welcome"
        href: index.qmd
      - sidebar:setup
      - sidebar:schedule
      - sidebar:assessments

  sidebar:
    - id: setup
      title: "Setting Up"
      style: "docked"
      collapse-level: 2
      background: light
      contents:
        - text: "Getting Started"
          href: setup/index.qmd
        - section: "Requirements"
          title: "Requirements"
          contents:
          - text: "Health Check"
            href: setup/health.qmd
          - text: "Base Utilities"
            href: setup/base.qmd
          - text: "Code Camp"
            href: setup/code_camp.qmd
        - section: "Installation"
          contents:
          - setup/git.qmd
          - setup/markdown.qmd
          - setup/env.qmd
        - text: "No Install Options"
          href: setup/no_install.qmd

    - id: assessments
      title: "Assessments"
      contents:
        - text: "Assessments"
          href: assessments/index.qmd
        - section: "Elements"
          contents:
          - assessments/audit.qmd
          - section: "Data+Policy Briefing (50%)"
            href: assessments/group.qmd
            contents:
              - assessments/briefing.qmd
              - assessments/code.qmd
              - assessments/models.qmd
              - assessments/restrictions.qmd
              - assessments/marking.qmd
          - assessments/individual.qmd
      
    - id: schedule
      title: "Week-by-Week"
      contents:
        - text: "Overview"
          href: sessions/index.qmd
        - section: "Week-by-Week"
          contents:
            - text: "1. Setting Up"
              href: sessions/week1.qmd
            - text: "2. Foundations (Pt.1)"
              href: sessions/week2.qmd
            - text: "3. Foundations (Pt.2)"
              href: sessions/week3.qmd
            - text: "4. Objects"
              href: sessions/week4.qmd
            - text: "5. Numeric Data"
              href: sessions/week5.qmd
            - text: "Reading Week"
              href: sessions/reading_week.qmd
            - text: "6. Spatial Data"
              href: sessions/week6.qmd
            - text: "7. Textual Data"
              href: sessions/week7.qmd
            - text: "8. Dimensions in Data"
              href: sessions/week8.qmd
            - text: "9. Visualising Data"
              href: sessions/week9.qmd
            - text: "10. Grouping Data"
              href: sessions/week10.qmd
        - text: "References"
          href: references.qmd

book: 
  title: "Foundations of Spatial Data Science"
  author: "Jon Reades"
  image: "/img/CASA_Logo_no_text.png"
  date: "6/1/2022"
  repo-url: https://github.com/jreades/fsds/
  repo-actions: [edit]
  chapters:
    - index.qmd
    - format.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - week9.qmd
    - week10.qmd
    - week11.qmd
    - assessments.qmd
    - references.qmd
  appendices:
    - appendices/docker.qmd
    - appendices/conda.qmd
  number-depth: 3
  toc-depth: 3
  sidebar:
    title: "CASA0013"
    style: floating
    reader-mode: true
  navbar:
    logo: "/img/CASA_Logo_no_text.png"
    collapse: true
    collapse-below: lg
    background: light
  favicon: "/img/favicon.ico"	
  page-navigation: true
  page-footer: 
    left: "Copyright 2022, Jon Reades" 
    right: 
      - icon: github
        href: https://github.com/jreades/fsds
      - icon: twitter 
        href: https://twitter.com/jreades

bibliography: bib/Readings.bib
csl: bib/chicago-author-date.csl

highlight-style: pygments
format:
  html:
    theme: 
      - minty
      - css/web.scss
    code-copy: true
    code-link: true
    #cover-image: cover.png
    toc: true
    toc-title: "On this page"
    toc-depth: 2
    toc_float: 
      collapsed: false
      smooth_scroll: true
  pdf:
    #cover-image: cover-highres.png
    documentclass: scrbook
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
